language: node_js
node_js:
  - "9"
  - "8"
  - "6"

env:
  global:
    secure: XnGZNm6Z4iJ7yCdPqVURbJ9U/9JcaAJtaUv/j2PateLwQAlNI9zs2Q79T2VplFHNwBsZ+Kne2z8gM9o6yWhMjfPTnlLQjv8d1En+EdgPNTkab8d/uUaaiLQFjFXJ2YSPD+VmnMJ0rIRqe/hAvTozzvf7ob1HgDO4t8neOW+OiPo=

compiler: gcc
sudo: false

os:
  - linux
  - osx

osx_image: xcode9.2

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="gcc-4.8";
      export CXX="g++-4.8";
      export LINK="gcc-4.8";
      export LINKXX="g++-4.8";
    fi
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      brew update;
      brew install vips --with-webp --with-graphicsmagick;
      brew install python;
      export PATH="/usr/local/opt/python/libexec/bin:$PATH";
      export TMPDIR="/tmp/";
    fi
  - nvm --version
  - node --version
  - npm --version
  - gcc --version
  - g++ --version
  - python --version
  - npm config set python `which python`

script:
  - npm install
  - npm test

cache:
  directories:
  - $HOME/.node-gyp
  - $HOME/.npm
  - node_modules

before_deploy:
  - (cd .. && tar --exclude='.git' -zcf mango-cli-$TRAVIS_OS_NAME-node$TRAVIS_NODE_VERSION-$TRAVIS_TAG.tar.gz -C $TRAVIS_BUILD_DIR .)
deploy:
  provider: releases
  api_key: $GHAUTH
  file: $TRAVIS_BUILD_DIR/../mango-cli-$TRAVIS_OS_NAME-node$TRAVIS_NODE_VERSION-$TRAVIS_TAG.tar.gz
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
